//go:build ignore

// Code generator for visitor pattern
// Run with: go run gen_visit.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
)

type InstructionInfo struct {
	Name     string
	Category string
	HasBody  bool
	BodyType string // "Body", "Then/Else", etc.
}

func main() {
	fset := token.NewFileSet()

	// Parse all instruction files
	files := []string{
		"control.go",
		"reference.go",
		"parametric.go",
		"variable.go",
		"memory.go",
		"numeric.go",
		"conversion.go",
		"extended.go",
	}

	instructions := make(map[string]*InstructionInfo)
	wrappers := []string{"Control", "Reference", "Parametric", "Variable", "Memory", "Numeric"}

	for _, filename := range files {
		f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", filename, err)
			continue
		}

		// Find all struct types and their marker methods
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				name := typeSpec.Name.Name
				info := &InstructionInfo{Name: name}

				// Check for Body field
				if structType.Fields != nil {
					for _, field := range structType.Fields.List {
						if len(field.Names) > 0 {
							fieldName := field.Names[0].Name
							if fieldName == "Body" {
								info.HasBody = true
								info.BodyType = "Body"
							} else if fieldName == "Then" {
								info.HasBody = true
								info.BodyType = "Then/Else"
							}
						}
					}
				}

				instructions[name] = info
			}
		}

		// Find marker methods to categorize instructions
		for _, decl := range f.Decls {
			funcDecl, ok := decl.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
				continue
			}

			// Get receiver type name
			var recvName string
			switch recv := funcDecl.Recv.List[0].Type.(type) {
			case *ast.Ident:
				recvName = recv.Name
			}

			if recvName == "" {
				continue
			}

			// Check for marker methods
			funcName := funcDecl.Name.Name
			if info, exists := instructions[recvName]; exists {
				switch funcName {
				case "controlInstr":
					info.Category = "control"
				case "referenceInstr":
					info.Category = "reference"
				case "parametricInstr":
					info.Category = "parametric"
				case "variableInstr":
					info.Category = "variable"
				case "memoryInstr":
					info.Category = "memory"
				case "numericInstr":
					info.Category = "numeric"
				}
			}
		}
	}

	// Generate the output
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen_visit.go. DO NOT EDIT.\n\n")
	buf.WriteString("package instruction\n\n")

	// Generate Visitor interface
	buf.WriteString("// Visitor visits WASM instructions.\n")
	buf.WriteString("type Visitor interface {\n")

	// Add wrapper type visit methods
	for _, wrapper := range wrappers {
		buf.WriteString(fmt.Sprintf("\tVisit%s(%s)\n", wrapper, wrapper))
	}
	buf.WriteString("\n")

	// Sort instructions by name for consistent output
	var names []string
	for name := range instructions {
		names = append(names, name)
	}
	sort.Strings(names)

	// Group by category
	categories := []string{"control", "reference", "parametric", "variable", "memory", "numeric"}
	categoryNames := map[string]string{
		"control":    "Control instructions",
		"reference":  "Reference instructions",
		"parametric": "Parametric instructions",
		"variable":   "Variable instructions",
		"memory":     "Memory instructions",
		"numeric":    "Numeric instructions",
	}

	for _, category := range categories {
		buf.WriteString(fmt.Sprintf("\t// %s\n", categoryNames[category]))
		for _, name := range names {
			info := instructions[name]
			if info.Category == category {
				buf.WriteString(fmt.Sprintf("\tVisit%s(%s)\n", name, name))
			}
		}
		buf.WriteString("\n")
	}

	buf.WriteString("}\n\n")

	// Generate VisitWith methods for wrapper types
	buf.WriteString("// VisitWith methods for wrapper types\n\n")
	for _, wrapper := range wrappers {
		buf.WriteString(fmt.Sprintf("func (c %s) VisitWith(v Visitor) { c.Instr.VisitWith(v) }\n", wrapper))
	}
	buf.WriteString("\n")

	// Generate VisitChildrenWith methods for wrapper types
	buf.WriteString("// VisitChildrenWith methods for wrapper types\n\n")
	for _, wrapper := range wrappers {
		buf.WriteString(fmt.Sprintf("func (c %s) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }\n", wrapper))
	}
	buf.WriteString("\n")

	// Generate VisitWith methods for all instructions
	buf.WriteString("// VisitWith methods for all instruction types\n\n")
	for _, name := range names {
		buf.WriteString(fmt.Sprintf("func (i %s) VisitWith(v Visitor) { v.Visit%s(i) }\n", name, name))
	}
	buf.WriteString("\n")

	// Generate VisitChildrenWith methods
	buf.WriteString("// VisitChildrenWith methods for all instruction types\n\n")
	for _, name := range names {
		info := instructions[name]
		if info.HasBody {
			if info.BodyType == "Body" {
				buf.WriteString(fmt.Sprintf("func (i %s) VisitChildrenWith(v Visitor) {\n", name))
				buf.WriteString("\tfor _, instr := range i.Body {\n")
				buf.WriteString("\t\tinstr.VisitWith(v)\n")
				buf.WriteString("\t}\n")
				buf.WriteString("}\n\n")
			} else if info.BodyType == "Then/Else" {
				buf.WriteString(fmt.Sprintf("func (i %s) VisitChildrenWith(v Visitor) {\n", name))
				buf.WriteString("\tfor _, instr := range i.Then {\n")
				buf.WriteString("\t\tinstr.VisitWith(v)\n")
				buf.WriteString("\t}\n")
				buf.WriteString("\tfor _, instr := range i.Else {\n")
				buf.WriteString("\t\tinstr.VisitWith(v)\n")
				buf.WriteString("\t}\n")
				buf.WriteString("}\n\n")
			}
		} else {
			buf.WriteString(fmt.Sprintf("func (i %s) VisitChildrenWith(v Visitor) {}\n", name))
		}
	}

	// Generate NoopVisitor
	buf.WriteString("// NoopVisitor is a visitor that does nothing but traverse children.\n")
	buf.WriteString("// Embed this in your visitor to only implement the methods you care about.\n")
	buf.WriteString("type NoopVisitor struct{}\n\n")

	// Generate NoopVisitor wrapper methods
	for _, wrapper := range wrappers {
		buf.WriteString(fmt.Sprintf("func (NoopVisitor) Visit%s(i %s) { i.VisitChildrenWith(NoopVisitor{}) }\n", wrapper, wrapper))
	}
	buf.WriteString("\n")

	// Generate NoopVisitor methods for all instructions
	for _, name := range names {
		info := instructions[name]
		if info.HasBody {
			buf.WriteString(fmt.Sprintf("func (NoopVisitor) Visit%s(i %s) { i.VisitChildrenWith(NoopVisitor{}) }\n", name, name))
		} else {
			buf.WriteString(fmt.Sprintf("func (NoopVisitor) Visit%s(i %s) {}\n", name, name))
		}
	}

	// Write to file
	err := os.WriteFile("visit.go", buf.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing visit.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generated visit.go successfully")
}
