// Code generated by gen_visit.go. DO NOT EDIT.

package instruction

// Visitor visits WASM instructions.
type Visitor interface {
	VisitControl(Control)
	VisitReference(Reference)
	VisitParametric(Parametric)
	VisitVariable(Variable)
	VisitMemory(Memory)
	VisitNumeric(Numeric)

	// Control instructions
	VisitBlock(Block)
	VisitBr(Br)
	VisitBrIf(BrIf)
	VisitBrTable(BrTable)
	VisitCall(Call)
	VisitCallIndirect(CallIndirect)
	VisitIf(If)
	VisitLoop(Loop)
	VisitNop(Nop)
	VisitReturn(Return)
	VisitUnreachable(Unreachable)

	// Reference instructions
	VisitRefFunc(RefFunc)
	VisitRefIsNull(RefIsNull)
	VisitRefNull(RefNull)

	// Parametric instructions
	VisitDrop(Drop)
	VisitSelect(Select)
	VisitSelectT(SelectT)

	// Variable instructions
	VisitElemDrop(ElemDrop)
	VisitGlobalGet(GlobalGet)
	VisitGlobalSet(GlobalSet)
	VisitLocalGet(LocalGet)
	VisitLocalSet(LocalSet)
	VisitLocalTee(LocalTee)
	VisitTableCopy(TableCopy)
	VisitTableFill(TableFill)
	VisitTableGet(TableGet)
	VisitTableGrow(TableGrow)
	VisitTableInit(TableInit)
	VisitTableSet(TableSet)
	VisitTableSize(TableSize)

	// Memory instructions
	VisitDataDrop(DataDrop)
	VisitF32Load(F32Load)
	VisitF32Store(F32Store)
	VisitF64Load(F64Load)
	VisitF64Store(F64Store)
	VisitI32Load(I32Load)
	VisitI32Load16S(I32Load16S)
	VisitI32Load16U(I32Load16U)
	VisitI32Load8S(I32Load8S)
	VisitI32Load8U(I32Load8U)
	VisitI32Store(I32Store)
	VisitI32Store16(I32Store16)
	VisitI32Store8(I32Store8)
	VisitI64Load(I64Load)
	VisitI64Load16S(I64Load16S)
	VisitI64Load16U(I64Load16U)
	VisitI64Load32S(I64Load32S)
	VisitI64Load32U(I64Load32U)
	VisitI64Load8S(I64Load8S)
	VisitI64Load8U(I64Load8U)
	VisitI64Store(I64Store)
	VisitI64Store16(I64Store16)
	VisitI64Store32(I64Store32)
	VisitI64Store8(I64Store8)
	VisitMemoryCopy(MemoryCopy)
	VisitMemoryFill(MemoryFill)
	VisitMemoryGrow(MemoryGrow)
	VisitMemoryInit(MemoryInit)
	VisitMemorySize(MemorySize)

	// Numeric instructions
	VisitF32Abs(F32Abs)
	VisitF32Add(F32Add)
	VisitF32Ceil(F32Ceil)
	VisitF32Const(F32Const)
	VisitF32ConvertI32S(F32ConvertI32S)
	VisitF32ConvertI32U(F32ConvertI32U)
	VisitF32ConvertI64S(F32ConvertI64S)
	VisitF32ConvertI64U(F32ConvertI64U)
	VisitF32Copysign(F32Copysign)
	VisitF32DemoteF64(F32DemoteF64)
	VisitF32Div(F32Div)
	VisitF32Eq(F32Eq)
	VisitF32Floor(F32Floor)
	VisitF32Ge(F32Ge)
	VisitF32Gt(F32Gt)
	VisitF32Le(F32Le)
	VisitF32Lt(F32Lt)
	VisitF32Max(F32Max)
	VisitF32Min(F32Min)
	VisitF32Mul(F32Mul)
	VisitF32Ne(F32Ne)
	VisitF32Nearest(F32Nearest)
	VisitF32Neg(F32Neg)
	VisitF32ReinterpretI32(F32ReinterpretI32)
	VisitF32Sqrt(F32Sqrt)
	VisitF32Sub(F32Sub)
	VisitF32Trunc(F32Trunc)
	VisitF64Abs(F64Abs)
	VisitF64Add(F64Add)
	VisitF64Ceil(F64Ceil)
	VisitF64Const(F64Const)
	VisitF64ConvertI32S(F64ConvertI32S)
	VisitF64ConvertI32U(F64ConvertI32U)
	VisitF64ConvertI64S(F64ConvertI64S)
	VisitF64ConvertI64U(F64ConvertI64U)
	VisitF64Copysign(F64Copysign)
	VisitF64Div(F64Div)
	VisitF64Eq(F64Eq)
	VisitF64Floor(F64Floor)
	VisitF64Ge(F64Ge)
	VisitF64Gt(F64Gt)
	VisitF64Le(F64Le)
	VisitF64Lt(F64Lt)
	VisitF64Max(F64Max)
	VisitF64Min(F64Min)
	VisitF64Mul(F64Mul)
	VisitF64Ne(F64Ne)
	VisitF64Nearest(F64Nearest)
	VisitF64Neg(F64Neg)
	VisitF64PromoteF32(F64PromoteF32)
	VisitF64ReinterpretI64(F64ReinterpretI64)
	VisitF64Sqrt(F64Sqrt)
	VisitF64Sub(F64Sub)
	VisitF64Trunc(F64Trunc)
	VisitI32Add(I32Add)
	VisitI32And(I32And)
	VisitI32Clz(I32Clz)
	VisitI32Const(I32Const)
	VisitI32Ctz(I32Ctz)
	VisitI32DivS(I32DivS)
	VisitI32DivU(I32DivU)
	VisitI32Eq(I32Eq)
	VisitI32Eqz(I32Eqz)
	VisitI32Extend16S(I32Extend16S)
	VisitI32Extend8S(I32Extend8S)
	VisitI32GeS(I32GeS)
	VisitI32GeU(I32GeU)
	VisitI32GtS(I32GtS)
	VisitI32GtU(I32GtU)
	VisitI32LeS(I32LeS)
	VisitI32LeU(I32LeU)
	VisitI32LtS(I32LtS)
	VisitI32LtU(I32LtU)
	VisitI32Mul(I32Mul)
	VisitI32Ne(I32Ne)
	VisitI32Or(I32Or)
	VisitI32Popcnt(I32Popcnt)
	VisitI32ReinterpretF32(I32ReinterpretF32)
	VisitI32RemS(I32RemS)
	VisitI32RemU(I32RemU)
	VisitI32Rotl(I32Rotl)
	VisitI32Rotr(I32Rotr)
	VisitI32Shl(I32Shl)
	VisitI32ShrS(I32ShrS)
	VisitI32ShrU(I32ShrU)
	VisitI32Sub(I32Sub)
	VisitI32TruncF32S(I32TruncF32S)
	VisitI32TruncF32U(I32TruncF32U)
	VisitI32TruncF64S(I32TruncF64S)
	VisitI32TruncF64U(I32TruncF64U)
	VisitI32TruncSatF32S(I32TruncSatF32S)
	VisitI32TruncSatF32U(I32TruncSatF32U)
	VisitI32TruncSatF64S(I32TruncSatF64S)
	VisitI32TruncSatF64U(I32TruncSatF64U)
	VisitI32WrapI64(I32WrapI64)
	VisitI32Xor(I32Xor)
	VisitI64Add(I64Add)
	VisitI64And(I64And)
	VisitI64Clz(I64Clz)
	VisitI64Const(I64Const)
	VisitI64Ctz(I64Ctz)
	VisitI64DivS(I64DivS)
	VisitI64DivU(I64DivU)
	VisitI64Eq(I64Eq)
	VisitI64Eqz(I64Eqz)
	VisitI64Extend16S(I64Extend16S)
	VisitI64Extend32S(I64Extend32S)
	VisitI64Extend8S(I64Extend8S)
	VisitI64ExtendI32S(I64ExtendI32S)
	VisitI64ExtendI32U(I64ExtendI32U)
	VisitI64GeS(I64GeS)
	VisitI64GeU(I64GeU)
	VisitI64GtS(I64GtS)
	VisitI64GtU(I64GtU)
	VisitI64LeS(I64LeS)
	VisitI64LeU(I64LeU)
	VisitI64LtS(I64LtS)
	VisitI64LtU(I64LtU)
	VisitI64Mul(I64Mul)
	VisitI64Ne(I64Ne)
	VisitI64Or(I64Or)
	VisitI64Popcnt(I64Popcnt)
	VisitI64ReinterpretF64(I64ReinterpretF64)
	VisitI64RemS(I64RemS)
	VisitI64RemU(I64RemU)
	VisitI64Rotl(I64Rotl)
	VisitI64Rotr(I64Rotr)
	VisitI64Shl(I64Shl)
	VisitI64ShrS(I64ShrS)
	VisitI64ShrU(I64ShrU)
	VisitI64Sub(I64Sub)
	VisitI64TruncF32S(I64TruncF32S)
	VisitI64TruncF32U(I64TruncF32U)
	VisitI64TruncF64S(I64TruncF64S)
	VisitI64TruncF64U(I64TruncF64U)
	VisitI64TruncSatF32S(I64TruncSatF32S)
	VisitI64TruncSatF32U(I64TruncSatF32U)
	VisitI64TruncSatF64S(I64TruncSatF64S)
	VisitI64TruncSatF64U(I64TruncSatF64U)
	VisitI64Xor(I64Xor)

}

// VisitWith methods for wrapper types

func (c Control) VisitWith(v Visitor) { c.Instr.VisitWith(v) }
func (c Reference) VisitWith(v Visitor) { c.Instr.VisitWith(v) }
func (c Parametric) VisitWith(v Visitor) { c.Instr.VisitWith(v) }
func (c Variable) VisitWith(v Visitor) { c.Instr.VisitWith(v) }
func (c Memory) VisitWith(v Visitor) { c.Instr.VisitWith(v) }
func (c Numeric) VisitWith(v Visitor) { c.Instr.VisitWith(v) }

// VisitChildrenWith methods for wrapper types

func (c Control) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }
func (c Reference) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }
func (c Parametric) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }
func (c Variable) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }
func (c Memory) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }
func (c Numeric) VisitChildrenWith(v Visitor) { c.Instr.VisitChildrenWith(v) }

// VisitWith methods for all instruction types

func (i Block) VisitWith(v Visitor) { v.VisitBlock(i) }
func (i Br) VisitWith(v Visitor) { v.VisitBr(i) }
func (i BrIf) VisitWith(v Visitor) { v.VisitBrIf(i) }
func (i BrTable) VisitWith(v Visitor) { v.VisitBrTable(i) }
func (i Call) VisitWith(v Visitor) { v.VisitCall(i) }
func (i CallIndirect) VisitWith(v Visitor) { v.VisitCallIndirect(i) }
func (i DataDrop) VisitWith(v Visitor) { v.VisitDataDrop(i) }
func (i Drop) VisitWith(v Visitor) { v.VisitDrop(i) }
func (i ElemDrop) VisitWith(v Visitor) { v.VisitElemDrop(i) }
func (i F32Abs) VisitWith(v Visitor) { v.VisitF32Abs(i) }
func (i F32Add) VisitWith(v Visitor) { v.VisitF32Add(i) }
func (i F32Ceil) VisitWith(v Visitor) { v.VisitF32Ceil(i) }
func (i F32Const) VisitWith(v Visitor) { v.VisitF32Const(i) }
func (i F32ConvertI32S) VisitWith(v Visitor) { v.VisitF32ConvertI32S(i) }
func (i F32ConvertI32U) VisitWith(v Visitor) { v.VisitF32ConvertI32U(i) }
func (i F32ConvertI64S) VisitWith(v Visitor) { v.VisitF32ConvertI64S(i) }
func (i F32ConvertI64U) VisitWith(v Visitor) { v.VisitF32ConvertI64U(i) }
func (i F32Copysign) VisitWith(v Visitor) { v.VisitF32Copysign(i) }
func (i F32DemoteF64) VisitWith(v Visitor) { v.VisitF32DemoteF64(i) }
func (i F32Div) VisitWith(v Visitor) { v.VisitF32Div(i) }
func (i F32Eq) VisitWith(v Visitor) { v.VisitF32Eq(i) }
func (i F32Floor) VisitWith(v Visitor) { v.VisitF32Floor(i) }
func (i F32Ge) VisitWith(v Visitor) { v.VisitF32Ge(i) }
func (i F32Gt) VisitWith(v Visitor) { v.VisitF32Gt(i) }
func (i F32Le) VisitWith(v Visitor) { v.VisitF32Le(i) }
func (i F32Load) VisitWith(v Visitor) { v.VisitF32Load(i) }
func (i F32Lt) VisitWith(v Visitor) { v.VisitF32Lt(i) }
func (i F32Max) VisitWith(v Visitor) { v.VisitF32Max(i) }
func (i F32Min) VisitWith(v Visitor) { v.VisitF32Min(i) }
func (i F32Mul) VisitWith(v Visitor) { v.VisitF32Mul(i) }
func (i F32Ne) VisitWith(v Visitor) { v.VisitF32Ne(i) }
func (i F32Nearest) VisitWith(v Visitor) { v.VisitF32Nearest(i) }
func (i F32Neg) VisitWith(v Visitor) { v.VisitF32Neg(i) }
func (i F32ReinterpretI32) VisitWith(v Visitor) { v.VisitF32ReinterpretI32(i) }
func (i F32Sqrt) VisitWith(v Visitor) { v.VisitF32Sqrt(i) }
func (i F32Store) VisitWith(v Visitor) { v.VisitF32Store(i) }
func (i F32Sub) VisitWith(v Visitor) { v.VisitF32Sub(i) }
func (i F32Trunc) VisitWith(v Visitor) { v.VisitF32Trunc(i) }
func (i F64Abs) VisitWith(v Visitor) { v.VisitF64Abs(i) }
func (i F64Add) VisitWith(v Visitor) { v.VisitF64Add(i) }
func (i F64Ceil) VisitWith(v Visitor) { v.VisitF64Ceil(i) }
func (i F64Const) VisitWith(v Visitor) { v.VisitF64Const(i) }
func (i F64ConvertI32S) VisitWith(v Visitor) { v.VisitF64ConvertI32S(i) }
func (i F64ConvertI32U) VisitWith(v Visitor) { v.VisitF64ConvertI32U(i) }
func (i F64ConvertI64S) VisitWith(v Visitor) { v.VisitF64ConvertI64S(i) }
func (i F64ConvertI64U) VisitWith(v Visitor) { v.VisitF64ConvertI64U(i) }
func (i F64Copysign) VisitWith(v Visitor) { v.VisitF64Copysign(i) }
func (i F64Div) VisitWith(v Visitor) { v.VisitF64Div(i) }
func (i F64Eq) VisitWith(v Visitor) { v.VisitF64Eq(i) }
func (i F64Floor) VisitWith(v Visitor) { v.VisitF64Floor(i) }
func (i F64Ge) VisitWith(v Visitor) { v.VisitF64Ge(i) }
func (i F64Gt) VisitWith(v Visitor) { v.VisitF64Gt(i) }
func (i F64Le) VisitWith(v Visitor) { v.VisitF64Le(i) }
func (i F64Load) VisitWith(v Visitor) { v.VisitF64Load(i) }
func (i F64Lt) VisitWith(v Visitor) { v.VisitF64Lt(i) }
func (i F64Max) VisitWith(v Visitor) { v.VisitF64Max(i) }
func (i F64Min) VisitWith(v Visitor) { v.VisitF64Min(i) }
func (i F64Mul) VisitWith(v Visitor) { v.VisitF64Mul(i) }
func (i F64Ne) VisitWith(v Visitor) { v.VisitF64Ne(i) }
func (i F64Nearest) VisitWith(v Visitor) { v.VisitF64Nearest(i) }
func (i F64Neg) VisitWith(v Visitor) { v.VisitF64Neg(i) }
func (i F64PromoteF32) VisitWith(v Visitor) { v.VisitF64PromoteF32(i) }
func (i F64ReinterpretI64) VisitWith(v Visitor) { v.VisitF64ReinterpretI64(i) }
func (i F64Sqrt) VisitWith(v Visitor) { v.VisitF64Sqrt(i) }
func (i F64Store) VisitWith(v Visitor) { v.VisitF64Store(i) }
func (i F64Sub) VisitWith(v Visitor) { v.VisitF64Sub(i) }
func (i F64Trunc) VisitWith(v Visitor) { v.VisitF64Trunc(i) }
func (i GlobalGet) VisitWith(v Visitor) { v.VisitGlobalGet(i) }
func (i GlobalSet) VisitWith(v Visitor) { v.VisitGlobalSet(i) }
func (i I32Add) VisitWith(v Visitor) { v.VisitI32Add(i) }
func (i I32And) VisitWith(v Visitor) { v.VisitI32And(i) }
func (i I32Clz) VisitWith(v Visitor) { v.VisitI32Clz(i) }
func (i I32Const) VisitWith(v Visitor) { v.VisitI32Const(i) }
func (i I32Ctz) VisitWith(v Visitor) { v.VisitI32Ctz(i) }
func (i I32DivS) VisitWith(v Visitor) { v.VisitI32DivS(i) }
func (i I32DivU) VisitWith(v Visitor) { v.VisitI32DivU(i) }
func (i I32Eq) VisitWith(v Visitor) { v.VisitI32Eq(i) }
func (i I32Eqz) VisitWith(v Visitor) { v.VisitI32Eqz(i) }
func (i I32Extend16S) VisitWith(v Visitor) { v.VisitI32Extend16S(i) }
func (i I32Extend8S) VisitWith(v Visitor) { v.VisitI32Extend8S(i) }
func (i I32GeS) VisitWith(v Visitor) { v.VisitI32GeS(i) }
func (i I32GeU) VisitWith(v Visitor) { v.VisitI32GeU(i) }
func (i I32GtS) VisitWith(v Visitor) { v.VisitI32GtS(i) }
func (i I32GtU) VisitWith(v Visitor) { v.VisitI32GtU(i) }
func (i I32LeS) VisitWith(v Visitor) { v.VisitI32LeS(i) }
func (i I32LeU) VisitWith(v Visitor) { v.VisitI32LeU(i) }
func (i I32Load) VisitWith(v Visitor) { v.VisitI32Load(i) }
func (i I32Load16S) VisitWith(v Visitor) { v.VisitI32Load16S(i) }
func (i I32Load16U) VisitWith(v Visitor) { v.VisitI32Load16U(i) }
func (i I32Load8S) VisitWith(v Visitor) { v.VisitI32Load8S(i) }
func (i I32Load8U) VisitWith(v Visitor) { v.VisitI32Load8U(i) }
func (i I32LtS) VisitWith(v Visitor) { v.VisitI32LtS(i) }
func (i I32LtU) VisitWith(v Visitor) { v.VisitI32LtU(i) }
func (i I32Mul) VisitWith(v Visitor) { v.VisitI32Mul(i) }
func (i I32Ne) VisitWith(v Visitor) { v.VisitI32Ne(i) }
func (i I32Or) VisitWith(v Visitor) { v.VisitI32Or(i) }
func (i I32Popcnt) VisitWith(v Visitor) { v.VisitI32Popcnt(i) }
func (i I32ReinterpretF32) VisitWith(v Visitor) { v.VisitI32ReinterpretF32(i) }
func (i I32RemS) VisitWith(v Visitor) { v.VisitI32RemS(i) }
func (i I32RemU) VisitWith(v Visitor) { v.VisitI32RemU(i) }
func (i I32Rotl) VisitWith(v Visitor) { v.VisitI32Rotl(i) }
func (i I32Rotr) VisitWith(v Visitor) { v.VisitI32Rotr(i) }
func (i I32Shl) VisitWith(v Visitor) { v.VisitI32Shl(i) }
func (i I32ShrS) VisitWith(v Visitor) { v.VisitI32ShrS(i) }
func (i I32ShrU) VisitWith(v Visitor) { v.VisitI32ShrU(i) }
func (i I32Store) VisitWith(v Visitor) { v.VisitI32Store(i) }
func (i I32Store16) VisitWith(v Visitor) { v.VisitI32Store16(i) }
func (i I32Store8) VisitWith(v Visitor) { v.VisitI32Store8(i) }
func (i I32Sub) VisitWith(v Visitor) { v.VisitI32Sub(i) }
func (i I32TruncF32S) VisitWith(v Visitor) { v.VisitI32TruncF32S(i) }
func (i I32TruncF32U) VisitWith(v Visitor) { v.VisitI32TruncF32U(i) }
func (i I32TruncF64S) VisitWith(v Visitor) { v.VisitI32TruncF64S(i) }
func (i I32TruncF64U) VisitWith(v Visitor) { v.VisitI32TruncF64U(i) }
func (i I32TruncSatF32S) VisitWith(v Visitor) { v.VisitI32TruncSatF32S(i) }
func (i I32TruncSatF32U) VisitWith(v Visitor) { v.VisitI32TruncSatF32U(i) }
func (i I32TruncSatF64S) VisitWith(v Visitor) { v.VisitI32TruncSatF64S(i) }
func (i I32TruncSatF64U) VisitWith(v Visitor) { v.VisitI32TruncSatF64U(i) }
func (i I32WrapI64) VisitWith(v Visitor) { v.VisitI32WrapI64(i) }
func (i I32Xor) VisitWith(v Visitor) { v.VisitI32Xor(i) }
func (i I64Add) VisitWith(v Visitor) { v.VisitI64Add(i) }
func (i I64And) VisitWith(v Visitor) { v.VisitI64And(i) }
func (i I64Clz) VisitWith(v Visitor) { v.VisitI64Clz(i) }
func (i I64Const) VisitWith(v Visitor) { v.VisitI64Const(i) }
func (i I64Ctz) VisitWith(v Visitor) { v.VisitI64Ctz(i) }
func (i I64DivS) VisitWith(v Visitor) { v.VisitI64DivS(i) }
func (i I64DivU) VisitWith(v Visitor) { v.VisitI64DivU(i) }
func (i I64Eq) VisitWith(v Visitor) { v.VisitI64Eq(i) }
func (i I64Eqz) VisitWith(v Visitor) { v.VisitI64Eqz(i) }
func (i I64Extend16S) VisitWith(v Visitor) { v.VisitI64Extend16S(i) }
func (i I64Extend32S) VisitWith(v Visitor) { v.VisitI64Extend32S(i) }
func (i I64Extend8S) VisitWith(v Visitor) { v.VisitI64Extend8S(i) }
func (i I64ExtendI32S) VisitWith(v Visitor) { v.VisitI64ExtendI32S(i) }
func (i I64ExtendI32U) VisitWith(v Visitor) { v.VisitI64ExtendI32U(i) }
func (i I64GeS) VisitWith(v Visitor) { v.VisitI64GeS(i) }
func (i I64GeU) VisitWith(v Visitor) { v.VisitI64GeU(i) }
func (i I64GtS) VisitWith(v Visitor) { v.VisitI64GtS(i) }
func (i I64GtU) VisitWith(v Visitor) { v.VisitI64GtU(i) }
func (i I64LeS) VisitWith(v Visitor) { v.VisitI64LeS(i) }
func (i I64LeU) VisitWith(v Visitor) { v.VisitI64LeU(i) }
func (i I64Load) VisitWith(v Visitor) { v.VisitI64Load(i) }
func (i I64Load16S) VisitWith(v Visitor) { v.VisitI64Load16S(i) }
func (i I64Load16U) VisitWith(v Visitor) { v.VisitI64Load16U(i) }
func (i I64Load32S) VisitWith(v Visitor) { v.VisitI64Load32S(i) }
func (i I64Load32U) VisitWith(v Visitor) { v.VisitI64Load32U(i) }
func (i I64Load8S) VisitWith(v Visitor) { v.VisitI64Load8S(i) }
func (i I64Load8U) VisitWith(v Visitor) { v.VisitI64Load8U(i) }
func (i I64LtS) VisitWith(v Visitor) { v.VisitI64LtS(i) }
func (i I64LtU) VisitWith(v Visitor) { v.VisitI64LtU(i) }
func (i I64Mul) VisitWith(v Visitor) { v.VisitI64Mul(i) }
func (i I64Ne) VisitWith(v Visitor) { v.VisitI64Ne(i) }
func (i I64Or) VisitWith(v Visitor) { v.VisitI64Or(i) }
func (i I64Popcnt) VisitWith(v Visitor) { v.VisitI64Popcnt(i) }
func (i I64ReinterpretF64) VisitWith(v Visitor) { v.VisitI64ReinterpretF64(i) }
func (i I64RemS) VisitWith(v Visitor) { v.VisitI64RemS(i) }
func (i I64RemU) VisitWith(v Visitor) { v.VisitI64RemU(i) }
func (i I64Rotl) VisitWith(v Visitor) { v.VisitI64Rotl(i) }
func (i I64Rotr) VisitWith(v Visitor) { v.VisitI64Rotr(i) }
func (i I64Shl) VisitWith(v Visitor) { v.VisitI64Shl(i) }
func (i I64ShrS) VisitWith(v Visitor) { v.VisitI64ShrS(i) }
func (i I64ShrU) VisitWith(v Visitor) { v.VisitI64ShrU(i) }
func (i I64Store) VisitWith(v Visitor) { v.VisitI64Store(i) }
func (i I64Store16) VisitWith(v Visitor) { v.VisitI64Store16(i) }
func (i I64Store32) VisitWith(v Visitor) { v.VisitI64Store32(i) }
func (i I64Store8) VisitWith(v Visitor) { v.VisitI64Store8(i) }
func (i I64Sub) VisitWith(v Visitor) { v.VisitI64Sub(i) }
func (i I64TruncF32S) VisitWith(v Visitor) { v.VisitI64TruncF32S(i) }
func (i I64TruncF32U) VisitWith(v Visitor) { v.VisitI64TruncF32U(i) }
func (i I64TruncF64S) VisitWith(v Visitor) { v.VisitI64TruncF64S(i) }
func (i I64TruncF64U) VisitWith(v Visitor) { v.VisitI64TruncF64U(i) }
func (i I64TruncSatF32S) VisitWith(v Visitor) { v.VisitI64TruncSatF32S(i) }
func (i I64TruncSatF32U) VisitWith(v Visitor) { v.VisitI64TruncSatF32U(i) }
func (i I64TruncSatF64S) VisitWith(v Visitor) { v.VisitI64TruncSatF64S(i) }
func (i I64TruncSatF64U) VisitWith(v Visitor) { v.VisitI64TruncSatF64U(i) }
func (i I64Xor) VisitWith(v Visitor) { v.VisitI64Xor(i) }
func (i If) VisitWith(v Visitor) { v.VisitIf(i) }
func (i LocalGet) VisitWith(v Visitor) { v.VisitLocalGet(i) }
func (i LocalSet) VisitWith(v Visitor) { v.VisitLocalSet(i) }
func (i LocalTee) VisitWith(v Visitor) { v.VisitLocalTee(i) }
func (i Loop) VisitWith(v Visitor) { v.VisitLoop(i) }
func (i MemoryCopy) VisitWith(v Visitor) { v.VisitMemoryCopy(i) }
func (i MemoryFill) VisitWith(v Visitor) { v.VisitMemoryFill(i) }
func (i MemoryGrow) VisitWith(v Visitor) { v.VisitMemoryGrow(i) }
func (i MemoryInit) VisitWith(v Visitor) { v.VisitMemoryInit(i) }
func (i MemorySize) VisitWith(v Visitor) { v.VisitMemorySize(i) }
func (i Nop) VisitWith(v Visitor) { v.VisitNop(i) }
func (i RefFunc) VisitWith(v Visitor) { v.VisitRefFunc(i) }
func (i RefIsNull) VisitWith(v Visitor) { v.VisitRefIsNull(i) }
func (i RefNull) VisitWith(v Visitor) { v.VisitRefNull(i) }
func (i Return) VisitWith(v Visitor) { v.VisitReturn(i) }
func (i Select) VisitWith(v Visitor) { v.VisitSelect(i) }
func (i SelectT) VisitWith(v Visitor) { v.VisitSelectT(i) }
func (i TableCopy) VisitWith(v Visitor) { v.VisitTableCopy(i) }
func (i TableFill) VisitWith(v Visitor) { v.VisitTableFill(i) }
func (i TableGet) VisitWith(v Visitor) { v.VisitTableGet(i) }
func (i TableGrow) VisitWith(v Visitor) { v.VisitTableGrow(i) }
func (i TableInit) VisitWith(v Visitor) { v.VisitTableInit(i) }
func (i TableSet) VisitWith(v Visitor) { v.VisitTableSet(i) }
func (i TableSize) VisitWith(v Visitor) { v.VisitTableSize(i) }
func (i Unreachable) VisitWith(v Visitor) { v.VisitUnreachable(i) }

// VisitChildrenWith methods for all instruction types

func (i Block) VisitChildrenWith(v Visitor) {
	for _, instr := range i.Body {
		instr.VisitWith(v)
	}
}

func (i Br) VisitChildrenWith(v Visitor) {}
func (i BrIf) VisitChildrenWith(v Visitor) {}
func (i BrTable) VisitChildrenWith(v Visitor) {}
func (i Call) VisitChildrenWith(v Visitor) {}
func (i CallIndirect) VisitChildrenWith(v Visitor) {}
func (i DataDrop) VisitChildrenWith(v Visitor) {}
func (i Drop) VisitChildrenWith(v Visitor) {}
func (i ElemDrop) VisitChildrenWith(v Visitor) {}
func (i F32Abs) VisitChildrenWith(v Visitor) {}
func (i F32Add) VisitChildrenWith(v Visitor) {}
func (i F32Ceil) VisitChildrenWith(v Visitor) {}
func (i F32Const) VisitChildrenWith(v Visitor) {}
func (i F32ConvertI32S) VisitChildrenWith(v Visitor) {}
func (i F32ConvertI32U) VisitChildrenWith(v Visitor) {}
func (i F32ConvertI64S) VisitChildrenWith(v Visitor) {}
func (i F32ConvertI64U) VisitChildrenWith(v Visitor) {}
func (i F32Copysign) VisitChildrenWith(v Visitor) {}
func (i F32DemoteF64) VisitChildrenWith(v Visitor) {}
func (i F32Div) VisitChildrenWith(v Visitor) {}
func (i F32Eq) VisitChildrenWith(v Visitor) {}
func (i F32Floor) VisitChildrenWith(v Visitor) {}
func (i F32Ge) VisitChildrenWith(v Visitor) {}
func (i F32Gt) VisitChildrenWith(v Visitor) {}
func (i F32Le) VisitChildrenWith(v Visitor) {}
func (i F32Load) VisitChildrenWith(v Visitor) {}
func (i F32Lt) VisitChildrenWith(v Visitor) {}
func (i F32Max) VisitChildrenWith(v Visitor) {}
func (i F32Min) VisitChildrenWith(v Visitor) {}
func (i F32Mul) VisitChildrenWith(v Visitor) {}
func (i F32Ne) VisitChildrenWith(v Visitor) {}
func (i F32Nearest) VisitChildrenWith(v Visitor) {}
func (i F32Neg) VisitChildrenWith(v Visitor) {}
func (i F32ReinterpretI32) VisitChildrenWith(v Visitor) {}
func (i F32Sqrt) VisitChildrenWith(v Visitor) {}
func (i F32Store) VisitChildrenWith(v Visitor) {}
func (i F32Sub) VisitChildrenWith(v Visitor) {}
func (i F32Trunc) VisitChildrenWith(v Visitor) {}
func (i F64Abs) VisitChildrenWith(v Visitor) {}
func (i F64Add) VisitChildrenWith(v Visitor) {}
func (i F64Ceil) VisitChildrenWith(v Visitor) {}
func (i F64Const) VisitChildrenWith(v Visitor) {}
func (i F64ConvertI32S) VisitChildrenWith(v Visitor) {}
func (i F64ConvertI32U) VisitChildrenWith(v Visitor) {}
func (i F64ConvertI64S) VisitChildrenWith(v Visitor) {}
func (i F64ConvertI64U) VisitChildrenWith(v Visitor) {}
func (i F64Copysign) VisitChildrenWith(v Visitor) {}
func (i F64Div) VisitChildrenWith(v Visitor) {}
func (i F64Eq) VisitChildrenWith(v Visitor) {}
func (i F64Floor) VisitChildrenWith(v Visitor) {}
func (i F64Ge) VisitChildrenWith(v Visitor) {}
func (i F64Gt) VisitChildrenWith(v Visitor) {}
func (i F64Le) VisitChildrenWith(v Visitor) {}
func (i F64Load) VisitChildrenWith(v Visitor) {}
func (i F64Lt) VisitChildrenWith(v Visitor) {}
func (i F64Max) VisitChildrenWith(v Visitor) {}
func (i F64Min) VisitChildrenWith(v Visitor) {}
func (i F64Mul) VisitChildrenWith(v Visitor) {}
func (i F64Ne) VisitChildrenWith(v Visitor) {}
func (i F64Nearest) VisitChildrenWith(v Visitor) {}
func (i F64Neg) VisitChildrenWith(v Visitor) {}
func (i F64PromoteF32) VisitChildrenWith(v Visitor) {}
func (i F64ReinterpretI64) VisitChildrenWith(v Visitor) {}
func (i F64Sqrt) VisitChildrenWith(v Visitor) {}
func (i F64Store) VisitChildrenWith(v Visitor) {}
func (i F64Sub) VisitChildrenWith(v Visitor) {}
func (i F64Trunc) VisitChildrenWith(v Visitor) {}
func (i GlobalGet) VisitChildrenWith(v Visitor) {}
func (i GlobalSet) VisitChildrenWith(v Visitor) {}
func (i I32Add) VisitChildrenWith(v Visitor) {}
func (i I32And) VisitChildrenWith(v Visitor) {}
func (i I32Clz) VisitChildrenWith(v Visitor) {}
func (i I32Const) VisitChildrenWith(v Visitor) {}
func (i I32Ctz) VisitChildrenWith(v Visitor) {}
func (i I32DivS) VisitChildrenWith(v Visitor) {}
func (i I32DivU) VisitChildrenWith(v Visitor) {}
func (i I32Eq) VisitChildrenWith(v Visitor) {}
func (i I32Eqz) VisitChildrenWith(v Visitor) {}
func (i I32Extend16S) VisitChildrenWith(v Visitor) {}
func (i I32Extend8S) VisitChildrenWith(v Visitor) {}
func (i I32GeS) VisitChildrenWith(v Visitor) {}
func (i I32GeU) VisitChildrenWith(v Visitor) {}
func (i I32GtS) VisitChildrenWith(v Visitor) {}
func (i I32GtU) VisitChildrenWith(v Visitor) {}
func (i I32LeS) VisitChildrenWith(v Visitor) {}
func (i I32LeU) VisitChildrenWith(v Visitor) {}
func (i I32Load) VisitChildrenWith(v Visitor) {}
func (i I32Load16S) VisitChildrenWith(v Visitor) {}
func (i I32Load16U) VisitChildrenWith(v Visitor) {}
func (i I32Load8S) VisitChildrenWith(v Visitor) {}
func (i I32Load8U) VisitChildrenWith(v Visitor) {}
func (i I32LtS) VisitChildrenWith(v Visitor) {}
func (i I32LtU) VisitChildrenWith(v Visitor) {}
func (i I32Mul) VisitChildrenWith(v Visitor) {}
func (i I32Ne) VisitChildrenWith(v Visitor) {}
func (i I32Or) VisitChildrenWith(v Visitor) {}
func (i I32Popcnt) VisitChildrenWith(v Visitor) {}
func (i I32ReinterpretF32) VisitChildrenWith(v Visitor) {}
func (i I32RemS) VisitChildrenWith(v Visitor) {}
func (i I32RemU) VisitChildrenWith(v Visitor) {}
func (i I32Rotl) VisitChildrenWith(v Visitor) {}
func (i I32Rotr) VisitChildrenWith(v Visitor) {}
func (i I32Shl) VisitChildrenWith(v Visitor) {}
func (i I32ShrS) VisitChildrenWith(v Visitor) {}
func (i I32ShrU) VisitChildrenWith(v Visitor) {}
func (i I32Store) VisitChildrenWith(v Visitor) {}
func (i I32Store16) VisitChildrenWith(v Visitor) {}
func (i I32Store8) VisitChildrenWith(v Visitor) {}
func (i I32Sub) VisitChildrenWith(v Visitor) {}
func (i I32TruncF32S) VisitChildrenWith(v Visitor) {}
func (i I32TruncF32U) VisitChildrenWith(v Visitor) {}
func (i I32TruncF64S) VisitChildrenWith(v Visitor) {}
func (i I32TruncF64U) VisitChildrenWith(v Visitor) {}
func (i I32TruncSatF32S) VisitChildrenWith(v Visitor) {}
func (i I32TruncSatF32U) VisitChildrenWith(v Visitor) {}
func (i I32TruncSatF64S) VisitChildrenWith(v Visitor) {}
func (i I32TruncSatF64U) VisitChildrenWith(v Visitor) {}
func (i I32WrapI64) VisitChildrenWith(v Visitor) {}
func (i I32Xor) VisitChildrenWith(v Visitor) {}
func (i I64Add) VisitChildrenWith(v Visitor) {}
func (i I64And) VisitChildrenWith(v Visitor) {}
func (i I64Clz) VisitChildrenWith(v Visitor) {}
func (i I64Const) VisitChildrenWith(v Visitor) {}
func (i I64Ctz) VisitChildrenWith(v Visitor) {}
func (i I64DivS) VisitChildrenWith(v Visitor) {}
func (i I64DivU) VisitChildrenWith(v Visitor) {}
func (i I64Eq) VisitChildrenWith(v Visitor) {}
func (i I64Eqz) VisitChildrenWith(v Visitor) {}
func (i I64Extend16S) VisitChildrenWith(v Visitor) {}
func (i I64Extend32S) VisitChildrenWith(v Visitor) {}
func (i I64Extend8S) VisitChildrenWith(v Visitor) {}
func (i I64ExtendI32S) VisitChildrenWith(v Visitor) {}
func (i I64ExtendI32U) VisitChildrenWith(v Visitor) {}
func (i I64GeS) VisitChildrenWith(v Visitor) {}
func (i I64GeU) VisitChildrenWith(v Visitor) {}
func (i I64GtS) VisitChildrenWith(v Visitor) {}
func (i I64GtU) VisitChildrenWith(v Visitor) {}
func (i I64LeS) VisitChildrenWith(v Visitor) {}
func (i I64LeU) VisitChildrenWith(v Visitor) {}
func (i I64Load) VisitChildrenWith(v Visitor) {}
func (i I64Load16S) VisitChildrenWith(v Visitor) {}
func (i I64Load16U) VisitChildrenWith(v Visitor) {}
func (i I64Load32S) VisitChildrenWith(v Visitor) {}
func (i I64Load32U) VisitChildrenWith(v Visitor) {}
func (i I64Load8S) VisitChildrenWith(v Visitor) {}
func (i I64Load8U) VisitChildrenWith(v Visitor) {}
func (i I64LtS) VisitChildrenWith(v Visitor) {}
func (i I64LtU) VisitChildrenWith(v Visitor) {}
func (i I64Mul) VisitChildrenWith(v Visitor) {}
func (i I64Ne) VisitChildrenWith(v Visitor) {}
func (i I64Or) VisitChildrenWith(v Visitor) {}
func (i I64Popcnt) VisitChildrenWith(v Visitor) {}
func (i I64ReinterpretF64) VisitChildrenWith(v Visitor) {}
func (i I64RemS) VisitChildrenWith(v Visitor) {}
func (i I64RemU) VisitChildrenWith(v Visitor) {}
func (i I64Rotl) VisitChildrenWith(v Visitor) {}
func (i I64Rotr) VisitChildrenWith(v Visitor) {}
func (i I64Shl) VisitChildrenWith(v Visitor) {}
func (i I64ShrS) VisitChildrenWith(v Visitor) {}
func (i I64ShrU) VisitChildrenWith(v Visitor) {}
func (i I64Store) VisitChildrenWith(v Visitor) {}
func (i I64Store16) VisitChildrenWith(v Visitor) {}
func (i I64Store32) VisitChildrenWith(v Visitor) {}
func (i I64Store8) VisitChildrenWith(v Visitor) {}
func (i I64Sub) VisitChildrenWith(v Visitor) {}
func (i I64TruncF32S) VisitChildrenWith(v Visitor) {}
func (i I64TruncF32U) VisitChildrenWith(v Visitor) {}
func (i I64TruncF64S) VisitChildrenWith(v Visitor) {}
func (i I64TruncF64U) VisitChildrenWith(v Visitor) {}
func (i I64TruncSatF32S) VisitChildrenWith(v Visitor) {}
func (i I64TruncSatF32U) VisitChildrenWith(v Visitor) {}
func (i I64TruncSatF64S) VisitChildrenWith(v Visitor) {}
func (i I64TruncSatF64U) VisitChildrenWith(v Visitor) {}
func (i I64Xor) VisitChildrenWith(v Visitor) {}
func (i If) VisitChildrenWith(v Visitor) {
	for _, instr := range i.Then {
		instr.VisitWith(v)
	}
	for _, instr := range i.Else {
		instr.VisitWith(v)
	}
}

func (i LocalGet) VisitChildrenWith(v Visitor) {}
func (i LocalSet) VisitChildrenWith(v Visitor) {}
func (i LocalTee) VisitChildrenWith(v Visitor) {}
func (i Loop) VisitChildrenWith(v Visitor) {
	for _, instr := range i.Body {
		instr.VisitWith(v)
	}
}

func (i MemoryCopy) VisitChildrenWith(v Visitor) {}
func (i MemoryFill) VisitChildrenWith(v Visitor) {}
func (i MemoryGrow) VisitChildrenWith(v Visitor) {}
func (i MemoryInit) VisitChildrenWith(v Visitor) {}
func (i MemorySize) VisitChildrenWith(v Visitor) {}
func (i Nop) VisitChildrenWith(v Visitor) {}
func (i RefFunc) VisitChildrenWith(v Visitor) {}
func (i RefIsNull) VisitChildrenWith(v Visitor) {}
func (i RefNull) VisitChildrenWith(v Visitor) {}
func (i Return) VisitChildrenWith(v Visitor) {}
func (i Select) VisitChildrenWith(v Visitor) {}
func (i SelectT) VisitChildrenWith(v Visitor) {}
func (i TableCopy) VisitChildrenWith(v Visitor) {}
func (i TableFill) VisitChildrenWith(v Visitor) {}
func (i TableGet) VisitChildrenWith(v Visitor) {}
func (i TableGrow) VisitChildrenWith(v Visitor) {}
func (i TableInit) VisitChildrenWith(v Visitor) {}
func (i TableSet) VisitChildrenWith(v Visitor) {}
func (i TableSize) VisitChildrenWith(v Visitor) {}
func (i Unreachable) VisitChildrenWith(v Visitor) {}
// NoopVisitor is a visitor that does nothing but traverse children.
// Embed this in your visitor to only implement the methods you care about.
type NoopVisitor struct{}

func (NoopVisitor) VisitControl(i Control) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitReference(i Reference) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitParametric(i Parametric) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitVariable(i Variable) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitMemory(i Memory) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitNumeric(i Numeric) { i.VisitChildrenWith(NoopVisitor{}) }

func (NoopVisitor) VisitBlock(i Block) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitBr(i Br) {}
func (NoopVisitor) VisitBrIf(i BrIf) {}
func (NoopVisitor) VisitBrTable(i BrTable) {}
func (NoopVisitor) VisitCall(i Call) {}
func (NoopVisitor) VisitCallIndirect(i CallIndirect) {}
func (NoopVisitor) VisitDataDrop(i DataDrop) {}
func (NoopVisitor) VisitDrop(i Drop) {}
func (NoopVisitor) VisitElemDrop(i ElemDrop) {}
func (NoopVisitor) VisitF32Abs(i F32Abs) {}
func (NoopVisitor) VisitF32Add(i F32Add) {}
func (NoopVisitor) VisitF32Ceil(i F32Ceil) {}
func (NoopVisitor) VisitF32Const(i F32Const) {}
func (NoopVisitor) VisitF32ConvertI32S(i F32ConvertI32S) {}
func (NoopVisitor) VisitF32ConvertI32U(i F32ConvertI32U) {}
func (NoopVisitor) VisitF32ConvertI64S(i F32ConvertI64S) {}
func (NoopVisitor) VisitF32ConvertI64U(i F32ConvertI64U) {}
func (NoopVisitor) VisitF32Copysign(i F32Copysign) {}
func (NoopVisitor) VisitF32DemoteF64(i F32DemoteF64) {}
func (NoopVisitor) VisitF32Div(i F32Div) {}
func (NoopVisitor) VisitF32Eq(i F32Eq) {}
func (NoopVisitor) VisitF32Floor(i F32Floor) {}
func (NoopVisitor) VisitF32Ge(i F32Ge) {}
func (NoopVisitor) VisitF32Gt(i F32Gt) {}
func (NoopVisitor) VisitF32Le(i F32Le) {}
func (NoopVisitor) VisitF32Load(i F32Load) {}
func (NoopVisitor) VisitF32Lt(i F32Lt) {}
func (NoopVisitor) VisitF32Max(i F32Max) {}
func (NoopVisitor) VisitF32Min(i F32Min) {}
func (NoopVisitor) VisitF32Mul(i F32Mul) {}
func (NoopVisitor) VisitF32Ne(i F32Ne) {}
func (NoopVisitor) VisitF32Nearest(i F32Nearest) {}
func (NoopVisitor) VisitF32Neg(i F32Neg) {}
func (NoopVisitor) VisitF32ReinterpretI32(i F32ReinterpretI32) {}
func (NoopVisitor) VisitF32Sqrt(i F32Sqrt) {}
func (NoopVisitor) VisitF32Store(i F32Store) {}
func (NoopVisitor) VisitF32Sub(i F32Sub) {}
func (NoopVisitor) VisitF32Trunc(i F32Trunc) {}
func (NoopVisitor) VisitF64Abs(i F64Abs) {}
func (NoopVisitor) VisitF64Add(i F64Add) {}
func (NoopVisitor) VisitF64Ceil(i F64Ceil) {}
func (NoopVisitor) VisitF64Const(i F64Const) {}
func (NoopVisitor) VisitF64ConvertI32S(i F64ConvertI32S) {}
func (NoopVisitor) VisitF64ConvertI32U(i F64ConvertI32U) {}
func (NoopVisitor) VisitF64ConvertI64S(i F64ConvertI64S) {}
func (NoopVisitor) VisitF64ConvertI64U(i F64ConvertI64U) {}
func (NoopVisitor) VisitF64Copysign(i F64Copysign) {}
func (NoopVisitor) VisitF64Div(i F64Div) {}
func (NoopVisitor) VisitF64Eq(i F64Eq) {}
func (NoopVisitor) VisitF64Floor(i F64Floor) {}
func (NoopVisitor) VisitF64Ge(i F64Ge) {}
func (NoopVisitor) VisitF64Gt(i F64Gt) {}
func (NoopVisitor) VisitF64Le(i F64Le) {}
func (NoopVisitor) VisitF64Load(i F64Load) {}
func (NoopVisitor) VisitF64Lt(i F64Lt) {}
func (NoopVisitor) VisitF64Max(i F64Max) {}
func (NoopVisitor) VisitF64Min(i F64Min) {}
func (NoopVisitor) VisitF64Mul(i F64Mul) {}
func (NoopVisitor) VisitF64Ne(i F64Ne) {}
func (NoopVisitor) VisitF64Nearest(i F64Nearest) {}
func (NoopVisitor) VisitF64Neg(i F64Neg) {}
func (NoopVisitor) VisitF64PromoteF32(i F64PromoteF32) {}
func (NoopVisitor) VisitF64ReinterpretI64(i F64ReinterpretI64) {}
func (NoopVisitor) VisitF64Sqrt(i F64Sqrt) {}
func (NoopVisitor) VisitF64Store(i F64Store) {}
func (NoopVisitor) VisitF64Sub(i F64Sub) {}
func (NoopVisitor) VisitF64Trunc(i F64Trunc) {}
func (NoopVisitor) VisitGlobalGet(i GlobalGet) {}
func (NoopVisitor) VisitGlobalSet(i GlobalSet) {}
func (NoopVisitor) VisitI32Add(i I32Add) {}
func (NoopVisitor) VisitI32And(i I32And) {}
func (NoopVisitor) VisitI32Clz(i I32Clz) {}
func (NoopVisitor) VisitI32Const(i I32Const) {}
func (NoopVisitor) VisitI32Ctz(i I32Ctz) {}
func (NoopVisitor) VisitI32DivS(i I32DivS) {}
func (NoopVisitor) VisitI32DivU(i I32DivU) {}
func (NoopVisitor) VisitI32Eq(i I32Eq) {}
func (NoopVisitor) VisitI32Eqz(i I32Eqz) {}
func (NoopVisitor) VisitI32Extend16S(i I32Extend16S) {}
func (NoopVisitor) VisitI32Extend8S(i I32Extend8S) {}
func (NoopVisitor) VisitI32GeS(i I32GeS) {}
func (NoopVisitor) VisitI32GeU(i I32GeU) {}
func (NoopVisitor) VisitI32GtS(i I32GtS) {}
func (NoopVisitor) VisitI32GtU(i I32GtU) {}
func (NoopVisitor) VisitI32LeS(i I32LeS) {}
func (NoopVisitor) VisitI32LeU(i I32LeU) {}
func (NoopVisitor) VisitI32Load(i I32Load) {}
func (NoopVisitor) VisitI32Load16S(i I32Load16S) {}
func (NoopVisitor) VisitI32Load16U(i I32Load16U) {}
func (NoopVisitor) VisitI32Load8S(i I32Load8S) {}
func (NoopVisitor) VisitI32Load8U(i I32Load8U) {}
func (NoopVisitor) VisitI32LtS(i I32LtS) {}
func (NoopVisitor) VisitI32LtU(i I32LtU) {}
func (NoopVisitor) VisitI32Mul(i I32Mul) {}
func (NoopVisitor) VisitI32Ne(i I32Ne) {}
func (NoopVisitor) VisitI32Or(i I32Or) {}
func (NoopVisitor) VisitI32Popcnt(i I32Popcnt) {}
func (NoopVisitor) VisitI32ReinterpretF32(i I32ReinterpretF32) {}
func (NoopVisitor) VisitI32RemS(i I32RemS) {}
func (NoopVisitor) VisitI32RemU(i I32RemU) {}
func (NoopVisitor) VisitI32Rotl(i I32Rotl) {}
func (NoopVisitor) VisitI32Rotr(i I32Rotr) {}
func (NoopVisitor) VisitI32Shl(i I32Shl) {}
func (NoopVisitor) VisitI32ShrS(i I32ShrS) {}
func (NoopVisitor) VisitI32ShrU(i I32ShrU) {}
func (NoopVisitor) VisitI32Store(i I32Store) {}
func (NoopVisitor) VisitI32Store16(i I32Store16) {}
func (NoopVisitor) VisitI32Store8(i I32Store8) {}
func (NoopVisitor) VisitI32Sub(i I32Sub) {}
func (NoopVisitor) VisitI32TruncF32S(i I32TruncF32S) {}
func (NoopVisitor) VisitI32TruncF32U(i I32TruncF32U) {}
func (NoopVisitor) VisitI32TruncF64S(i I32TruncF64S) {}
func (NoopVisitor) VisitI32TruncF64U(i I32TruncF64U) {}
func (NoopVisitor) VisitI32TruncSatF32S(i I32TruncSatF32S) {}
func (NoopVisitor) VisitI32TruncSatF32U(i I32TruncSatF32U) {}
func (NoopVisitor) VisitI32TruncSatF64S(i I32TruncSatF64S) {}
func (NoopVisitor) VisitI32TruncSatF64U(i I32TruncSatF64U) {}
func (NoopVisitor) VisitI32WrapI64(i I32WrapI64) {}
func (NoopVisitor) VisitI32Xor(i I32Xor) {}
func (NoopVisitor) VisitI64Add(i I64Add) {}
func (NoopVisitor) VisitI64And(i I64And) {}
func (NoopVisitor) VisitI64Clz(i I64Clz) {}
func (NoopVisitor) VisitI64Const(i I64Const) {}
func (NoopVisitor) VisitI64Ctz(i I64Ctz) {}
func (NoopVisitor) VisitI64DivS(i I64DivS) {}
func (NoopVisitor) VisitI64DivU(i I64DivU) {}
func (NoopVisitor) VisitI64Eq(i I64Eq) {}
func (NoopVisitor) VisitI64Eqz(i I64Eqz) {}
func (NoopVisitor) VisitI64Extend16S(i I64Extend16S) {}
func (NoopVisitor) VisitI64Extend32S(i I64Extend32S) {}
func (NoopVisitor) VisitI64Extend8S(i I64Extend8S) {}
func (NoopVisitor) VisitI64ExtendI32S(i I64ExtendI32S) {}
func (NoopVisitor) VisitI64ExtendI32U(i I64ExtendI32U) {}
func (NoopVisitor) VisitI64GeS(i I64GeS) {}
func (NoopVisitor) VisitI64GeU(i I64GeU) {}
func (NoopVisitor) VisitI64GtS(i I64GtS) {}
func (NoopVisitor) VisitI64GtU(i I64GtU) {}
func (NoopVisitor) VisitI64LeS(i I64LeS) {}
func (NoopVisitor) VisitI64LeU(i I64LeU) {}
func (NoopVisitor) VisitI64Load(i I64Load) {}
func (NoopVisitor) VisitI64Load16S(i I64Load16S) {}
func (NoopVisitor) VisitI64Load16U(i I64Load16U) {}
func (NoopVisitor) VisitI64Load32S(i I64Load32S) {}
func (NoopVisitor) VisitI64Load32U(i I64Load32U) {}
func (NoopVisitor) VisitI64Load8S(i I64Load8S) {}
func (NoopVisitor) VisitI64Load8U(i I64Load8U) {}
func (NoopVisitor) VisitI64LtS(i I64LtS) {}
func (NoopVisitor) VisitI64LtU(i I64LtU) {}
func (NoopVisitor) VisitI64Mul(i I64Mul) {}
func (NoopVisitor) VisitI64Ne(i I64Ne) {}
func (NoopVisitor) VisitI64Or(i I64Or) {}
func (NoopVisitor) VisitI64Popcnt(i I64Popcnt) {}
func (NoopVisitor) VisitI64ReinterpretF64(i I64ReinterpretF64) {}
func (NoopVisitor) VisitI64RemS(i I64RemS) {}
func (NoopVisitor) VisitI64RemU(i I64RemU) {}
func (NoopVisitor) VisitI64Rotl(i I64Rotl) {}
func (NoopVisitor) VisitI64Rotr(i I64Rotr) {}
func (NoopVisitor) VisitI64Shl(i I64Shl) {}
func (NoopVisitor) VisitI64ShrS(i I64ShrS) {}
func (NoopVisitor) VisitI64ShrU(i I64ShrU) {}
func (NoopVisitor) VisitI64Store(i I64Store) {}
func (NoopVisitor) VisitI64Store16(i I64Store16) {}
func (NoopVisitor) VisitI64Store32(i I64Store32) {}
func (NoopVisitor) VisitI64Store8(i I64Store8) {}
func (NoopVisitor) VisitI64Sub(i I64Sub) {}
func (NoopVisitor) VisitI64TruncF32S(i I64TruncF32S) {}
func (NoopVisitor) VisitI64TruncF32U(i I64TruncF32U) {}
func (NoopVisitor) VisitI64TruncF64S(i I64TruncF64S) {}
func (NoopVisitor) VisitI64TruncF64U(i I64TruncF64U) {}
func (NoopVisitor) VisitI64TruncSatF32S(i I64TruncSatF32S) {}
func (NoopVisitor) VisitI64TruncSatF32U(i I64TruncSatF32U) {}
func (NoopVisitor) VisitI64TruncSatF64S(i I64TruncSatF64S) {}
func (NoopVisitor) VisitI64TruncSatF64U(i I64TruncSatF64U) {}
func (NoopVisitor) VisitI64Xor(i I64Xor) {}
func (NoopVisitor) VisitIf(i If) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitLocalGet(i LocalGet) {}
func (NoopVisitor) VisitLocalSet(i LocalSet) {}
func (NoopVisitor) VisitLocalTee(i LocalTee) {}
func (NoopVisitor) VisitLoop(i Loop) { i.VisitChildrenWith(NoopVisitor{}) }
func (NoopVisitor) VisitMemoryCopy(i MemoryCopy) {}
func (NoopVisitor) VisitMemoryFill(i MemoryFill) {}
func (NoopVisitor) VisitMemoryGrow(i MemoryGrow) {}
func (NoopVisitor) VisitMemoryInit(i MemoryInit) {}
func (NoopVisitor) VisitMemorySize(i MemorySize) {}
func (NoopVisitor) VisitNop(i Nop) {}
func (NoopVisitor) VisitRefFunc(i RefFunc) {}
func (NoopVisitor) VisitRefIsNull(i RefIsNull) {}
func (NoopVisitor) VisitRefNull(i RefNull) {}
func (NoopVisitor) VisitReturn(i Return) {}
func (NoopVisitor) VisitSelect(i Select) {}
func (NoopVisitor) VisitSelectT(i SelectT) {}
func (NoopVisitor) VisitTableCopy(i TableCopy) {}
func (NoopVisitor) VisitTableFill(i TableFill) {}
func (NoopVisitor) VisitTableGet(i TableGet) {}
func (NoopVisitor) VisitTableGrow(i TableGrow) {}
func (NoopVisitor) VisitTableInit(i TableInit) {}
func (NoopVisitor) VisitTableSet(i TableSet) {}
func (NoopVisitor) VisitTableSize(i TableSize) {}
func (NoopVisitor) VisitUnreachable(i Unreachable) {}
